### ISSUE TITLE
User (index logged in) page

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#13]
What I need in context_dict:
1. msps - msps objects associated with the user (these objects must contain a match % value, or if they don't contain the value, find a way how to get the value to the template because I need that value for each msp)
2. comments - let's say 10 latest comments objects
3. laws - let's say 10 latest laws objects

**Comment by Cristinapisi** [comment]
done as well as getting the data in the template. 
still need to compute match accurately, currently returning 0.
Will close this issue and open a new one for computing match.
