### ISSUE TITLE
Rename images

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#23]
All letters in the images should be lowercase. 

Example:

DerekMacKay.jpg - When trying to access this image using concatenation of first and last name from database, it doesn't return anything, because in the database his last name is saved as Mackay. There are some more examples like this so it's better to have them all lowercase and then just concatenate first and last name and transfer it to lowercase as well.

OR somebody could go over all images and check for some of these things in there and just change them.

**Comment by emilcieslar** [comment]
Seems like Derek was the only guy who had his name wrong, otherwise we wouldn't have images on MSPs page. So no need to rename all, I just changed Derek.

**Comment by Cristinapisi** [comment]
It seems you haven't pushed as the photo is still with the wrong name. I cannot seem to push it with the right name either.

**Comment by emilcieslar** [comment]
It's changed on deployment though.
