### ISSUE TITLE
Add mailto to "Engage with your constituencies" button

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#33]
https://yoast.com/guide-mailto-links/

If you specify certain fields in mailto: you can create a new email with prefilled body and subject. In the subject there could be for example: "I want to engage!" and body would be: "I'm a representative, how do I get my credentials?"

This way we don't have to create another page.

**Comment by jamesrferguson** [comment]
Added mailto link

**Comment by Cristinapisi** [comment]
@jamesrferguson can you add an email to that and then close this issue? 

I created this account for us: representmemsp@gmail.com
If you want to log in pls ask me for the password somewhere else, as this is a public repository
