### ISSUE TITLE
Check whether all urls are not absolute

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#36]
All urls should be {% url 'nameoftheurl' %}

**Comment by Cristinapisi** [comment]
register seems to have a problem with the url 
![image](https://cloud.githubusercontent.com/assets/3392528/6754891/6d937d82-cf17-11e4-8008-07999c1f7d6f.png)

**Comment by emilcieslar** [comment]
the problem is now fixed in deployment

**Comment by Cristinapisi** [comment]
seems fine. will assume it works
