### ISSUE TITLE
On the MSP page, for the users MSPs, for each Law displayed, put the user vote next to the MSP vote

### ISSUE THREAD

**Issue by Cristinapisi** [emilcieslar/tangowithdjango#49]
Leif said this after the first presentation. 
So that it is obvious, beyond the match, where there are different opinions.

**Comment by Cristinapisi** [comment]
done, both views and template.
Not incredibly pretty, but entirely functional.

**Comment by emilcieslar** [comment]
That looks actually pretty good to be honest.
On 22 March 2015 at 16:09:06, Cristina (notifications@github.com) wrote:

done, both views and template.
Not incredibly pretty, but entirely functional.
