### ISSUE TITLE
List laws on MSP page from the latest to the oldest, now it's the opposite

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#52]

**Comment by Cristinapisi** [comment]
@emilcieslar , if you  are 100% sure it is the opposite and will be the opposite, there is a simple fix in the views.
If however, the database will not be populated in order on pythonanywhere (I don't know, might happen, you know better) I need to do some complicated magic in the views.

**Comment by emilcieslar** [comment]
If you go to list of laws on /laws/ you'll find S4M-11507 as the first one, on the other hand in MSP view it is the last one.
